version: 2
jobs:
  build:
    docker:
      - image: circleci/buildpack-deps:stretch
    working_directory: ~/forestry

    steps:
      - attach_workspace:
          at: ~/forestry

      - setup_remote_docker:
          version: 18.05.0-ce

      - run: docker login -u $DOCKER_USER -p $DOCKER_PASS

      - run:
          name: Build image
          command: |
            docker build . -t forestryio/resque-web:$CIRCLE_BUILD_NUM -t forestryio/resque-web:latest

      - deploy:
          name: Push image
          command: |
            docker push forestryio/api:$CIRCLE_BUILD_NUM
            docker push forestryio/resque-web:latest

workflows:
  version: 2
  deploy:
    jobs:
      - build