name: Docker Image CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v2

      - name: Login to docker
        run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Pull cache
        run: docker pull forestryio/resque-web:latest

      - name: Build the Docker image
        run: |
          docker build . \
            --file Dockerfile \
            --tag forestryio/resque-web:$(echo "${{ github.sha }}" | cut -c1-7) \
            --tag forestryio/resque-web:latest \
            --cache-from forestryio/resque-web:latest \

      - name: Push docker image
        run: docker push forestryio/resque-web:$(echo "${{ github.sha }}" | cut -c1-7)

      - name: Push latest tag
        if: github.ref == 'refs/heads/master'
        run: docker push forestryio/resque-web:latest